name: PyTest

on:
  push:
  pull_request:

env:
  COLUMNS: 120

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.14"]
    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.version }}

      - name: Install Dependencies
        run: make sync

      - name: Run Tests
        run: make test
